# Generated by Django 5.1.5 on 2025-03-15 06:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('approved', models.BooleanField(default=True)),
                ('phone_no', models.CharField(max_length=15, unique=True)),
                ('rights', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('driver', 'Driver')], default='customer', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Auto Rickshaw', 'Auto Rickshaw'), ('Economy Car', 'Economy Car'), ('Sedan', 'Sedan'), ('Luxury Car', 'Luxury Car')], max_length=20)),
                ('manufacture_date', models.DateField()),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_image', models.ImageField(upload_to='uploads/vehicles/')),
                ('password', models.CharField(max_length=50)),
                ('current_location', models.CharField(default='', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='Administrator.user')),
            ],
        ),
    ]
