# Generated by Django 5.1.5 on 2025-03-20 02:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fare', models.FloatField(default=30)),
                ('base_distance', models.FloatField(default=1.5)),
                ('rate_per_km', models.FloatField(default=15)),
                ('commission_rate', models.FloatField(default=0.1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle_type', models.CharField(choices=[('Auto Rickshaw', 'Auto Rickshaw'), ('Economy Car', 'Economy Car'), ('Sedan', 'Sedan'), ('Luxury Car', 'Luxury Car')], max_length=20)),
            ],
        ),
    ]
