# Generated by Django 5.1.5 on 2025-04-16 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0004_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='password',
        ),
    ]
